name: Frontend CI/CD

on:
  push:
    paths:
      - '**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        run: docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/cicd-frontend:latest --push .

  deploy:
    runs-on: [self-hosted, Linux, X64]
    needs: build-and-push
    steps:
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cicd-frontend:latest
      - name: Stop old container
        run: docker rm -f cicd-frontend || true
      - name: Run new container
        run: docker run -d --name cicd-frontend -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/cicd-frontend:latest